### ISSUE TITLE
3DPhysics with FMX

### ISSUE THREAD

**Issue by soinalastudio** [gbegreg/GBE3D#1]
Hello,
Thank you for your library. Is it possible to have 3D physics with your lib? It'll be helpfull. I can't find no library for that in the net. With Gorilla3D, it's possible but too expensive for me. 
Thank you Paul. 
Regards

**Comment by gbegreg** [comment]
Hello,
There is no 3D physics with my lib. Gorilla 3D use the Q3 physic engine (https://github.com/RandyGaul/qu3e). I don't know it but you can maybe use it.
Regards
PS : sorry for my poor english...
